# Use an official lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the preprocessing script
COPY ../data/preprocessing.py .

# Define the command to run the preprocessing script
CMD ["python", "preprocessing.py"]
